version: 2
updates:
  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "axondata/maintainers"
    labels:
      - "dependencies"
      - "go"
    
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "axondata/maintainers"
    labels:
      - "dependencies"
      - "github-actions"